#!/usr/bin/python3.3 -S
import fcntl
import json
import os
import subprocess
import urllib.parse
import tempfile
import termios
import time
import threading
import types

conf = json.loads(
    urllib.parse.unquote(os.environ['VIDO_CONFIG']),
    object_hook=lambda x: types.SimpleNamespace(**x))

# Open this early so that clear_dirs/rw_dirs won't interfere
exit_status_file = open(conf.ipc + '/exit-status', 'w')

if conf.virt != 'userns':
    # Do this before scanning mountinfo
    # Skip in userns (already mounted, and already namespaced)
    subprocess.check_call('mount -t proc proc /proc'.split())

mounted = []
def read_mounts():
    with open('/proc/self/mountinfo') as mounts:
        for line in mounts:
            items = line.split()
            idx = items.index('-')
            fstype = items[idx + 1]
            opts1 = items[5].split(',')
            opts2 = items[idx + 3].split(',')
            readonly = 'ro' in opts1 + opts2
            intpath = items[3]
            mpoint = items[4]
            dev = items[idx + 2]
            mounted.append((fstype, mpoint))

if conf.pivot_root:
    slash0 = tempfile.mkdtemp(prefix='vido-', suffix='.new-slash')
    delta0 = tempfile.mkdtemp(prefix='vido-', suffix='.delta-slash')
    subprocess.check_call('mount -t tmpfs tmpfs --'.split() + [delta0])
    read_mounts()
    subprocess.check_call(
        'mount -t overlayfs overlayfs'.split()
        + ['-olowerdir={},upperdir={}'.format('/', delta0), slash0])

    slash1 = tempfile.mkdtemp(
        prefix='vido-', suffix='.old-slash', dir=slash0)
    os.chdir(slash0)
    subprocess.check_call(['/sbin/pivot_root', slash0, slash1])
    os.chroot('.')
    slash1 = '/' + os.path.relpath(slash1, start=slash0)
    moved = set()
    for (fstype, mpoint) in mounted:
        if mpoint == '/':
            continue
        if mpoint in moved:
            continue
        if any(mpoint.startswith(mp + '/') for mp in moved):
            continue
        moved.add(mpoint)
        subprocess.check_call(
            'mount --move --'.split() + [slash1 + mpoint, mpoint])
else:
    read_mounts()


mounted = set(mounted)
def ensure_mount(fstype, mpoint):
    if (fstype, mpoint) in mounted:
        return
    subprocess.check_call('mount -t'.split() + [fstype, '--', fstype, mpoint])

ensure_mount('sysfs', '/sys')
ensure_mount('tmpfs', '/run')
os.mkdir('/run/lock')
os.mkdir('/run/shm')

# Or set CONFIG_DEVTMPFS_MOUNT
try:
    ensure_mount('devtmpfs', '/dev')
except subprocess.CalledProcessError:
    # XXX Debian/Ubuntu ship uml kernels without devtmpfs
    if conf.virt != 'uml':
        raise

if conf.watchdog:
    class Watchdog(threading.Thread):
        daemon = True

        def run(self):
            wd = open('/dev/watchdog', 'w')
            while True:
                wd.write('.')
                wd.flush()
                time.sleep(.5)

    Watchdog().start()

if not os.path.lexists('/dev/fd'):
    subprocess.check_call('ln -sT /proc/self/fd /dev/fd'.split())

# Set controlling tty
if conf.virt != 'userns':
    os.setsid()
    fcntl.ioctl(0, termios.TIOCSCTTY, 0)

    # Reset windows size
    # If this is resized after boot, call `resize` manually.
    # The guest won't get SIGWINCH.
    try:
        subprocess.call(['resize'], stdout=subprocess.DEVNULL)
    except FileNotFoundError:
        # Not installed
        pass

# At least the Debian and Ubuntu UML package uses this
if conf.virt == 'uml':
    subprocess.call(
        'mount -t hostfs -o /usr/lib/uml/modules hostfs /lib/modules'.split(),
        stderr=subprocess.DEVNULL)

env = vars(conf.env)


for dn in conf.rw_dirs:
    tdn = tempfile.mkdtemp(prefix='vido-', suffix='.delta')
    subprocess.check_call('mount -t tmpfs tmpfs --'.split() + [tdn])
    subprocess.check_call(
        'mount -t overlayfs overlayfs'.split()
        + ['-olowerdir={},upperdir={}'.format(dn, tdn), dn])

for dn in conf.clear_dirs:
    subprocess.check_call('mount -t tmpfs tmpfs --'.split() + [dn])

if hasattr(conf, 'net'):
    subprocess.check_call(
        'ip addr add dev eth0'.split() + [conf.net.host])
    subprocess.check_call('ip link set eth0 up'.split())
    subprocess.check_call(
        'ip route add default via'.split() + [conf.net.router]
        + 'dev eth0'.split())

for i, disk in enumerate(conf.disks):
    env['VIDO_DISK{}'.format(i)] = disk

rcode = subprocess.call(conf.cmd, cwd=conf.cwd, env=env)
exit_status_file.write('%d' % rcode)
exit_status_file.close()
if conf.virt != 'userns':
    subprocess.check_call('/sbin/poweroff -f'.split())

